-- CreateEnum
CREATE TYPE "Permission" AS ENUM ('VIEW_DASHBOARD', 'VIEW_CLIENTS', 'CREATE_CLIENT', 'EDIT_CLIENT', 'DELETE_CLIENT', 'VIEW_EXPORTERS', 'CREATE_EXPORTER', 'EDIT_EXPORTER', 'DELETE_EXPORTER', 'VIEW_CONSIGNEES', 'CREATE_CONSIGNEE', 'EDIT_CONSIGNEE', 'DELETE_CONSIGNEE', 'VIEW_SHIPMENTS', 'CREATE_SHIPMENT', 'EDIT_SHIPMENT', 'DELETE_SHIPMENT', 'VIEW_ALLOCATIONS', 'CREATE_ALLOCATION', 'EDIT_ALLOCATION', 'DELETE_ALLOCATION', 'VIEW_INVOICES', 'CREATE_INVOICE', 'EDIT_INVOICE', 'DELETE_INVOICE', 'VIEW_PACKING_LISTS', 'CREATE_PACKING_LIST', 'EDIT_PACKING_LIST', 'DELETE_PACKING_LIST', 'VIEW_CONTAINERS', 'CREATE_CONTAINER', 'EDIT_CONTAINER', 'DELETE_CONTAINER', 'VIEW_TRANSITS', 'CREATE_TRANSIT', 'EDIT_TRANSIT', 'DELETE_TRANSIT', 'VIEW_DOCUMENTS', 'UPLOAD_DOCUMENT', 'DELETE_DOCUMENT', 'VIEW_USERS', 'CREATE_USER', 'EDIT_USER', 'DELETE_USER', 'MANAGE_PERMISSIONS');

-- CreateTable
CREATE TABLE "UserPermission" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "permission" "Permission" NOT NULL,

    CONSTRAINT "UserPermission_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "UserPermission_userId_permission_key" ON "UserPermission"("userId", "permission");

-- AddForeignKey
ALTER TABLE "UserPermission" ADD CONSTRAINT "UserPermission_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
