export const PERMISSIONS = {
  VIEW_DASHBOARD: "VIEW_DASHBOARD",

  VIEW_CLIENTS: "VIEW_CLIENTS",
  CREATE_CLIENT: "CREATE_CLIENT",
  EDIT_CLIENT: "EDIT_CLIENT",
  DELETE_CLIENT: "DELETE_CLIENT",

  VIEW_EXPORTERS: "VIEW_EXPORTERS",
  CREATE_EXPORTER: "CREATE_EXPORTER",
  EDIT_EXPORTER: "EDIT_EXPORTER",
  DELETE_EXPORTER: "DELETE_EXPORTER",

  VIEW_CONSIGNEES: "VIEW_CONSIGNEES",
  CREATE_CONSIGNEE: "CREATE_CONSIGNEE",
  EDIT_CONSIGNEE: "EDIT_CONSIGNEE",
  DELETE_CONSIGNEE: "DELETE_CONSIGNEE",

  VIEW_SHIPMENTS: "VIEW_SHIPMENTS",
  CREATE_SHIPMENT: "CREATE_SHIPMENT",
  EDIT_SHIPMENT: "EDIT_SHIPMENT",
  DELETE_SHIPMENT: "DELETE_SHIPMENT",

  VIEW_ALLOCATIONS: "VIEW_ALLOCATIONS",
  CREATE_ALLOCATION: "CREATE_ALLOCATION",
  EDIT_ALLOCATION: "EDIT_ALLOCATION",
  DELETE_ALLOCATION: "DELETE_ALLOCATION",

  VIEW_INVOICES: "VIEW_INVOICES",
  CREATE_INVOICE: "CREATE_INVOICE",
  EDIT_INVOICE: "EDIT_INVOICE",
  DELETE_INVOICE: "DELETE_INVOICE",

  VIEW_PACKING_LISTS: "VIEW_PACKING_LISTS",
  CREATE_PACKING_LIST: "CREATE_PACKING_LIST",
  EDIT_PACKING_LIST: "EDIT_PACKING_LIST",
  DELETE_PACKING_LIST: "DELETE_PACKING_LIST",

  VIEW_CONTAINERS: "VIEW_CONTAINERS",
  CREATE_CONTAINER: "CREATE_CONTAINER",
  EDIT_CONTAINER: "EDIT_CONTAINER",
  DELETE_CONTAINER: "DELETE_CONTAINER",

  VIEW_TRANSITS: "VIEW_TRANSITS",
  CREATE_TRANSIT: "CREATE_TRANSIT",
  EDIT_TRANSIT: "EDIT_TRANSIT",
  DELETE_TRANSIT: "DELETE_TRANSIT",

  VIEW_DOCUMENTS: "VIEW_DOCUMENTS",
  UPLOAD_DOCUMENT: "UPLOAD_DOCUMENT",
  EDIT_DOCUMENT: "EDIT_DOCUMENT",
  DELETE_DOCUMENT: "DELETE_DOCUMENT",

  
  VIEW_GATES: "VIEW_GATES",
  UPLOAD_GATE: "UPLOAD_GATE",
  EDIT_GATE: "EDIT_GATE",
  DELETE_GATE: "DELETE_GATE",

  VIEW_USERS: "VIEW_USERS",
  CREATE_USER: "CREATE_USER",
  EDIT_USER: "EDIT_USER",
  DELETE_USER: "DELETE_USER",

  MANAGE_PERMISSIONS: "MANAGE_PERMISSIONS",
} as const;

export type Permission =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS];